In [8]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score
import pandas as pd

In [ ]:
df = pd.DataFrame({"name": ["홍길동", "이순신"], "age": [20, 30]})

df

  name  age
0  홍길동   20
1  이순신   30

In [13]:
data = df.to_json(orient="records")
print(type(data))


# to_json의 결과는 문자열이다

<class 'str'>

In [ ]:
data = df.to_json(orient="columns")
print(type(data))
data

<class 'str'>

'{"name":{"0":"\\ud64d\\uae38\\ub3d9","1":"\\uc774\\uc21c\\uc2e0"},"age":{"0":20,"1":30}}'

In [13]:
iris = load_iris()
X = pd.DataFrame(iris["data"], columns=iris["feature_names"])
y = pd.Series(iris["target"], name="target")

# Data 분할(x_train, x_test, y_train, y_test)
x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [14]:
type(x_train), type(x_test), type(y_train), type(y_test)

(pandas.core.frame.DataFrame,
 pandas.core.frame.DataFrame,
 pandas.core.series.Series,
 pandas.core.series.Series)

In [15]:
x_train.to_json()

'{"sepal length (cm)":{"22":4.6,"15":5.7,"65":6.7,"11":4.8,"42":4.4,"146":6.3,"51":6.4,"27":5.2,"4":5.0,"32":5.2,"142":5.8,"85":6.0,"86":6.7,"16":5.4,"10":5.4,"81":5.5,"133":6.3,"137":6.4,"75":6.6,"109":7.2,"96":5.7,"105":7.6,"66":5.6,"0":5.1,"122":7.7,"67":5.8,"28":5.2,"40":5.0,"44":5.1,"60":5.0,"123":6.3,"24":4.8,"25":5.0,"23":5.1,"94":5.6,"39":5.1,"95":5.7,"117":7.7,"47":4.6,"97":6.2,"113":5.7,"33":5.5,"138":6.0,"101":5.8,"62":6.0,"84":5.4,"148":6.2,"53":5.5,"5":5.4,"93":5.0,"111":6.4,"49":5.0,"35":5.0,"80":5.5,"77":6.7,"34":4.9,"114":5.8,"7":5.0,"43":5.0,"70":5.9,"98":5.1,"120":6.9,"83":6.0,"134":6.1,"135":7.7,"89":5.5,"8":4.4,"13":4.3,"119":6.0,"125":7.2,"3":4.6,"17":5.1,"38":4.4,"72":6.3,"136":6.3,"6":4.6,"112":6.8,"100":6.3,"2":4.7,"63":6.1,"54":6.5,"126":6.2,"50":7.0,"115":6.4,"46":5.1,"139":6.9,"61":5.9,"147":6.5,"79":5.7,"59":5.2,"91":6.1,"41":4.5,"58":6.6,"90":5.5,"48":5.3,"88":5.6,"107":7.3,"124":6.7,"21":5.1,"57":4.9,"144":6.7,"129":7.2,"37":4.9,"140":6.7,"1":4.9,"52":6.9,"130":7.4,"103":6.3,"99":5.7,"116":6.5,"87":6.3,"74":6.4,"121":5.6,"149":5.9,"20":5.4,"71":6.1,"106":4.9,"14":5.8,"92":5.8,"102":7.1},"sepal width (cm)":{"22":3.6,"15":4.4,"65":3.1,"11":3.4,"42":3.2,"146":2.5,"51":3.2,"27":3.5,"4":3.6,"32":4.1,"142":2.7,"85":3.4,"86":3.1,"16":3.9,"10":3.7,"81":2.4,"133":2.8,"137":3.1,"75":3.0,"109":3.6,"96":2.9,"105":3.0,"66":3.0,"0":3.5,"122":2.8,"67":2.7,"28":3.4,"40":3.5,"44":3.8,"60":2.0,"123":2.7,"24":3.4,"25":3.0,"23":3.3,"94":2.7,"39":3.4,"95":3.0,"117":3.8,"47":3.2,"97":2.9,"113":2.5,"33":4.2,"138":3.0,"101":2.7,"62":2.2,"84":3.0,"148":3.4,"53":2.3,"5":3.9,"93":2.3,"111":2.7,"49":3.3,"35":3.2,"80":2.4,"77":3.0,"34":3.1,"114":2.8,"7":3.4,"43":3.5,"70":3.2,"98":2.5,"120":3.2,"83":2.7,"134":2.6,"135":3.0,"89":2.5,"8":2.9,"13":3.0,"119":2.2,"125":3.2,"3":3.1,"17":3.5,"38":3.0,"72":2.5,"136":3.4,"6":3.4,"112":3.0,"100":3.3,"2":3.2,"63":2.9,"54":2.8,"126":2.8,"50":3.2,"115":3.2,"46":3.8,"139":3.1,"61":3.0,"147":3.0,"79":2.6,"59":2.7,"91":3.0,"41":2.3,"58":2.9,"90":2.6,"48":3.7,"88":3.0,"107":2.9,"124":3.3,"21":3.7,"57":2.4,"144":3.3,"129":3.0,"37":3.6,"140":3.1,"1":3.0,"52":3.1,"130":2.8,"103":2.9,"99":2.8,"116":3.0,"87":2.3,"74":2.9,"121":2.8,"149":3.0,"20":3.4,"71":2.8,"106":2.5,"14":4.0,"92":2.6,"102":3.0},"petal length (cm)":{"22":1.0,"15":1.5,"65":4.4,"11":1.6,"42":1.3,"146":5.0,"51":4.5,"27":1.5,"4":1.4,"32":1.5,"142":5.1,"85":4.5,"86":4.7,"16":1.3,"10":1.5,"81":3.7,"133":5.1,"137":5.5,"75":4.4,"109":6.1,"96":4.2,"105":6.6,"66":4.5,"0":1.4,"122":6.7,"67":4.1,"28":1.4,"40":1.3,"44":1.9,"60":3.5,"123":4.9,"24":1.9,"25":1.6,"23":1.7,"94":4.2,"39":1.5,"95":4.2,"117":6.7,"47":1.4,"97":4.3,"113":5.0,"33":1.4,"138":4.8,"101":5.1,"62":4.0,"84":4.5,"148":5.4,"53":4.0,"5":1.7,"93":3.3,"111":5.3,"49":1.4,"35":1.2,"80":3.8,"77":5.0,"34":1.5,"114":5.1,"7":1.5,"43":1.6,"70":4.8,"98":3.0,"120":5.7,"83":5.1,"134":5.6,"135":6.1,"89":4.0,"8":1.4,"13":1.1,"119":5.0,"125":6.0,"3":1.5,"17":1.4,"38":1.3,"72":4.9,"136":5.6,"6":1.4,"112":5.5,"100":6.0,"2":1.3,"63":4.7,"54":4.6,"126":4.8,"50":4.7,"115":5.3,"46":1.6,"139":5.4,"61":4.2,"147":5.2,"79":3.5,"59":3.9,"91":4.6,"41":1.3,"58":4.6,"90":4.4,"48":1.5,"88":4.1,"107":6.3,"124":5.7,"21":1.5,"57":3.3,"144":5.7,"129":5.8,"37":1.4,"140":5.6,"1":1.4,"52":4.9,"130":6.1,"103":5.6,"99":4.1,"116":5.5,"87":4.4,"74":4.3,"121":4.9,"149":5.1,"20":1.7,"71":4.0,"106":4.5,"14":1.2,"92":4.0,"102":5.9},"petal width (cm)":{"22":0.2,"15":0.4,"65":1.4,"11":0.2,"42":0.2,"146":1.9,"51":1.5,"27":0.2,"4":0.2,"32":0.1,"142":1.9,"85":1.6,"86":1.5,"16":0.4,"10":0.2,"81":1.0,"133":1.5,"137":1.8,"75":1.4,"109":2.5,"96":1.3,"105":2.1,"66":1.5,"0":0.2,"122":2.0,"67":1.0,"28":0.2,"40":0.3,"44":0.4,"60":1.0,"123":1.8,"24":0.2,"25":0.2,"23":0.5,"94":1.3,"39":0.2,"95":1.2,"117":2.2,"47":0.2,"97":1.3,"113":2.0,"33":0.2,"138":1.8,"101":1.9,"62":1.0,"84":1.5,"148":2.3,"53":1.3,"5":0.4,"93":1.0,"111":1.9,"49":0.2,"35":0.2,"80":1.1,"77":1.7,"34":0.2,"114":2.4,"7":0.2,"43":0.6,"70":1.8,"98":1.1,"120":2.3,"83":1.6,"134":1.4,"135":2.3,"89":1.3,"8":0.2,"13":0.1,"119":1.5,"125":1.8,"3":0.2,"17":0.3,"38":0.2,"72":1.5,"136":2.4,"6":0.3,"112":2.1,"100":2.5,"2":0.2,"63":1.4,"54":1.5,"126":1.8,"50":1.4,"115":2.3,"46":0.2,"139":2.1,"61":1.5,"147":2.0,"79":1.0,"59":1.4,"91":1.4,"41":0.3,"58":1.3,"90":1.2,"48":0.2,"88":1.3,"107":1.8,"124":2.1,"21":0.4,"57":1.0,"144":2.5,"129":1.6,"37":0.1,"140":2.4,"1":0.2,"52":1.5,"130":1.9,"103":1.8,"99":1.3,"116":1.8,"87":1.3,"74":1.3,"121":2.0,"149":1.8,"20":0.2,"71":1.3,"106":1.7,"14":0.2,"92":1.2,"102":2.1}}'

In [19]:
x_train.to_json(orient="columns")

'{"sepal length (cm)":{"22":4.6,"15":5.7,"65":6.7,"11":4.8,"42":4.4,"146":6.3,"51":6.4,"27":5.2,"4":5.0,"32":5.2,"142":5.8,"85":6.0,"86":6.7,"16":5.4,"10":5.4,"81":5.5,"133":6.3,"137":6.4,"75":6.6,"109":7.2,"96":5.7,"105":7.6,"66":5.6,"0":5.1,"122":7.7,"67":5.8,"28":5.2,"40":5.0,"44":5.1,"60":5.0,"123":6.3,"24":4.8,"25":5.0,"23":5.1,"94":5.6,"39":5.1,"95":5.7,"117":7.7,"47":4.6,"97":6.2,"113":5.7,"33":5.5,"138":6.0,"101":5.8,"62":6.0,"84":5.4,"148":6.2,"53":5.5,"5":5.4,"93":5.0,"111":6.4,"49":5.0,"35":5.0,"80":5.5,"77":6.7,"34":4.9,"114":5.8,"7":5.0,"43":5.0,"70":5.9,"98":5.1,"120":6.9,"83":6.0,"134":6.1,"135":7.7,"89":5.5,"8":4.4,"13":4.3,"119":6.0,"125":7.2,"3":4.6,"17":5.1,"38":4.4,"72":6.3,"136":6.3,"6":4.6,"112":6.8,"100":6.3,"2":4.7,"63":6.1,"54":6.5,"126":6.2,"50":7.0,"115":6.4,"46":5.1,"139":6.9,"61":5.9,"147":6.5,"79":5.7,"59":5.2,"91":6.1,"41":4.5,"58":6.6,"90":5.5,"48":5.3,"88":5.6,"107":7.3,"124":6.7,"21":5.1,"57":4.9,"144":6.7,"129":7.2,"37":4.9,"140":6.7,"1":4.9,"52":6.9,"130":7.4,"103":6.3,"99":5.7,"116":6.5,"87":6.3,"74":6.4,"121":5.6,"149":5.9,"20":5.4,"71":6.1,"106":4.9,"14":5.8,"92":5.8,"102":7.1},"sepal width (cm)":{"22":3.6,"15":4.4,"65":3.1,"11":3.4,"42":3.2,"146":2.5,"51":3.2,"27":3.5,"4":3.6,"32":4.1,"142":2.7,"85":3.4,"86":3.1,"16":3.9,"10":3.7,"81":2.4,"133":2.8,"137":3.1,"75":3.0,"109":3.6,"96":2.9,"105":3.0,"66":3.0,"0":3.5,"122":2.8,"67":2.7,"28":3.4,"40":3.5,"44":3.8,"60":2.0,"123":2.7,"24":3.4,"25":3.0,"23":3.3,"94":2.7,"39":3.4,"95":3.0,"117":3.8,"47":3.2,"97":2.9,"113":2.5,"33":4.2,"138":3.0,"101":2.7,"62":2.2,"84":3.0,"148":3.4,"53":2.3,"5":3.9,"93":2.3,"111":2.7,"49":3.3,"35":3.2,"80":2.4,"77":3.0,"34":3.1,"114":2.8,"7":3.4,"43":3.5,"70":3.2,"98":2.5,"120":3.2,"83":2.7,"134":2.6,"135":3.0,"89":2.5,"8":2.9,"13":3.0,"119":2.2,"125":3.2,"3":3.1,"17":3.5,"38":3.0,"72":2.5,"136":3.4,"6":3.4,"112":3.0,"100":3.3,"2":3.2,"63":2.9,"54":2.8,"126":2.8,"50":3.2,"115":3.2,"46":3.8,"139":3.1,"61":3.0,"147":3.0,"79":2.6,"59":2.7,"91":3.0,"41":2.3,"58":2.9,"90":2.6,"48":3.7,"88":3.0,"107":2.9,"124":3.3,"21":3.7,"57":2.4,"144":3.3,"129":3.0,"37":3.6,"140":3.1,"1":3.0,"52":3.1,"130":2.8,"103":2.9,"99":2.8,"116":3.0,"87":2.3,"74":2.9,"121":2.8,"149":3.0,"20":3.4,"71":2.8,"106":2.5,"14":4.0,"92":2.6,"102":3.0},"petal length (cm)":{"22":1.0,"15":1.5,"65":4.4,"11":1.6,"42":1.3,"146":5.0,"51":4.5,"27":1.5,"4":1.4,"32":1.5,"142":5.1,"85":4.5,"86":4.7,"16":1.3,"10":1.5,"81":3.7,"133":5.1,"137":5.5,"75":4.4,"109":6.1,"96":4.2,"105":6.6,"66":4.5,"0":1.4,"122":6.7,"67":4.1,"28":1.4,"40":1.3,"44":1.9,"60":3.5,"123":4.9,"24":1.9,"25":1.6,"23":1.7,"94":4.2,"39":1.5,"95":4.2,"117":6.7,"47":1.4,"97":4.3,"113":5.0,"33":1.4,"138":4.8,"101":5.1,"62":4.0,"84":4.5,"148":5.4,"53":4.0,"5":1.7,"93":3.3,"111":5.3,"49":1.4,"35":1.2,"80":3.8,"77":5.0,"34":1.5,"114":5.1,"7":1.5,"43":1.6,"70":4.8,"98":3.0,"120":5.7,"83":5.1,"134":5.6,"135":6.1,"89":4.0,"8":1.4,"13":1.1,"119":5.0,"125":6.0,"3":1.5,"17":1.4,"38":1.3,"72":4.9,"136":5.6,"6":1.4,"112":5.5,"100":6.0,"2":1.3,"63":4.7,"54":4.6,"126":4.8,"50":4.7,"115":5.3,"46":1.6,"139":5.4,"61":4.2,"147":5.2,"79":3.5,"59":3.9,"91":4.6,"41":1.3,"58":4.6,"90":4.4,"48":1.5,"88":4.1,"107":6.3,"124":5.7,"21":1.5,"57":3.3,"144":5.7,"129":5.8,"37":1.4,"140":5.6,"1":1.4,"52":4.9,"130":6.1,"103":5.6,"99":4.1,"116":5.5,"87":4.4,"74":4.3,"121":4.9,"149":5.1,"20":1.7,"71":4.0,"106":4.5,"14":1.2,"92":4.0,"102":5.9},"petal width (cm)":{"22":0.2,"15":0.4,"65":1.4,"11":0.2,"42":0.2,"146":1.9,"51":1.5,"27":0.2,"4":0.2,"32":0.1,"142":1.9,"85":1.6,"86":1.5,"16":0.4,"10":0.2,"81":1.0,"133":1.5,"137":1.8,"75":1.4,"109":2.5,"96":1.3,"105":2.1,"66":1.5,"0":0.2,"122":2.0,"67":1.0,"28":0.2,"40":0.3,"44":0.4,"60":1.0,"123":1.8,"24":0.2,"25":0.2,"23":0.5,"94":1.3,"39":0.2,"95":1.2,"117":2.2,"47":0.2,"97":1.3,"113":2.0,"33":0.2,"138":1.8,"101":1.9,"62":1.0,"84":1.5,"148":2.3,"53":1.3,"5":0.4,"93":1.0,"111":1.9,"49":0.2,"35":0.2,"80":1.1,"77":1.7,"34":0.2,"114":2.4,"7":0.2,"43":0.6,"70":1.8,"98":1.1,"120":2.3,"83":1.6,"134":1.4,"135":2.3,"89":1.3,"8":0.2,"13":0.1,"119":1.5,"125":1.8,"3":0.2,"17":0.3,"38":0.2,"72":1.5,"136":2.4,"6":0.3,"112":2.1,"100":2.5,"2":0.2,"63":1.4,"54":1.5,"126":1.8,"50":1.4,"115":2.3,"46":0.2,"139":2.1,"61":1.5,"147":2.0,"79":1.0,"59":1.4,"91":1.4,"41":0.3,"58":1.3,"90":1.2,"48":0.2,"88":1.3,"107":1.8,"124":2.1,"21":0.4,"57":1.0,"144":2.5,"129":1.6,"37":0.1,"140":2.4,"1":0.2,"52":1.5,"130":1.9,"103":1.8,"99":1.3,"116":1.8,"87":1.3,"74":1.3,"121":2.0,"149":1.8,"20":0.2,"71":1.3,"106":1.7,"14":0.2,"92":1.2,"102":2.1}}'

In [17]:
x_train.to_json(orient="records")

'[{"sepal length (cm)":4.6,"sepal width (cm)":3.6,"petal length (cm)":1.0,"petal width (cm)":0.2},{"sepal length (cm)":5.7,"sepal width (cm)":4.4,"petal length (cm)":1.5,"petal width (cm)":0.4},{"sepal length (cm)":6.7,"sepal width (cm)":3.1,"petal length (cm)":4.4,"petal width (cm)":1.4},{"sepal length (cm)":4.8,"sepal width (cm)":3.4,"petal length (cm)":1.6,"petal width (cm)":0.2},{"sepal length (cm)":4.4,"sepal width (cm)":3.2,"petal length (cm)":1.3,"petal width (cm)":0.2},{"sepal length (cm)":6.3,"sepal width (cm)":2.5,"petal length (cm)":5.0,"petal width (cm)":1.9},{"sepal length (cm)":6.4,"sepal width (cm)":3.2,"petal length (cm)":4.5,"petal width (cm)":1.5},{"sepal length (cm)":5.2,"sepal width (cm)":3.5,"petal length (cm)":1.5,"petal width (cm)":0.2},{"sepal length (cm)":5.0,"sepal width (cm)":3.6,"petal length (cm)":1.4,"petal width (cm)":0.2},{"sepal length (cm)":5.2,"sepal width (cm)":4.1,"petal length (cm)":1.5,"petal width (cm)":0.1},{"sepal length (cm)":5.8,"sepal width (cm)":2.7,"petal length (cm)":5.1,"petal width (cm)":1.9},{"sepal length (cm)":6.0,"sepal width (cm)":3.4,"petal length (cm)":4.5,"petal width (cm)":1.6},{"sepal length (cm)":6.7,"sepal width (cm)":3.1,"petal length (cm)":4.7,"petal width (cm)":1.5},{"sepal length (cm)":5.4,"sepal width (cm)":3.9,"petal length (cm)":1.3,"petal width (cm)":0.4},{"sepal length (cm)":5.4,"sepal width (cm)":3.7,"petal length (cm)":1.5,"petal width (cm)":0.2},{"sepal length (cm)":5.5,"sepal width (cm)":2.4,"petal length (cm)":3.7,"petal width (cm)":1.0},{"sepal length (cm)":6.3,"sepal width (cm)":2.8,"petal length (cm)":5.1,"petal width (cm)":1.5},{"sepal length (cm)":6.4,"sepal width (cm)":3.1,"petal length (cm)":5.5,"petal width (cm)":1.8},{"sepal length (cm)":6.6,"sepal width (cm)":3.0,"petal length (cm)":4.4,"petal width (cm)":1.4},{"sepal length (cm)":7.2,"sepal width (cm)":3.6,"petal length (cm)":6.1,"petal width (cm)":2.5},{"sepal length (cm)":5.7,"sepal width (cm)":2.9,"petal length (cm)":4.2,"petal width (cm)":1.3},{"sepal length (cm)":7.6,"sepal width (cm)":3.0,"petal length (cm)":6.6,"petal width (cm)":2.1},{"sepal length (cm)":5.6,"sepal width (cm)":3.0,"petal length (cm)":4.5,"petal width (cm)":1.5},{"sepal length (cm)":5.1,"sepal width (cm)":3.5,"petal length (cm)":1.4,"petal width (cm)":0.2},{"sepal length (cm)":7.7,"sepal width (cm)":2.8,"petal length (cm)":6.7,"petal width (cm)":2.0},{"sepal length (cm)":5.8,"sepal width (cm)":2.7,"petal length (cm)":4.1,"petal width (cm)":1.0},{"sepal length (cm)":5.2,"sepal width (cm)":3.4,"petal length (cm)":1.4,"petal width (cm)":0.2},{"sepal length (cm)":5.0,"sepal width (cm)":3.5,"petal length (cm)":1.3,"petal width (cm)":0.3},{"sepal length (cm)":5.1,"sepal width (cm)":3.8,"petal length (cm)":1.9,"petal width (cm)":0.4},{"sepal length (cm)":5.0,"sepal width (cm)":2.0,"petal length (cm)":3.5,"petal width (cm)":1.0},{"sepal length (cm)":6.3,"sepal width (cm)":2.7,"petal length (cm)":4.9,"petal width (cm)":1.8},{"sepal length (cm)":4.8,"sepal width (cm)":3.4,"petal length (cm)":1.9,"petal width (cm)":0.2},{"sepal length (cm)":5.0,"sepal width (cm)":3.0,"petal length (cm)":1.6,"petal width (cm)":0.2},{"sepal length (cm)":5.1,"sepal width (cm)":3.3,"petal length (cm)":1.7,"petal width (cm)":0.5},{"sepal length (cm)":5.6,"sepal width (cm)":2.7,"petal length (cm)":4.2,"petal width (cm)":1.3},{"sepal length (cm)":5.1,"sepal width (cm)":3.4,"petal length (cm)":1.5,"petal width (cm)":0.2},{"sepal length (cm)":5.7,"sepal width (cm)":3.0,"petal length (cm)":4.2,"petal width (cm)":1.2},{"sepal length (cm)":7.7,"sepal width (cm)":3.8,"petal length (cm)":6.7,"petal width (cm)":2.2},{"sepal length (cm)":4.6,"sepal width (cm)":3.2,"petal length (cm)":1.4,"petal width (cm)":0.2},{"sepal length (cm)":6.2,"sepal width (cm)":2.9,"petal length (cm)":4.3,"petal width (cm)":1.3},{"sepal length (cm)":5.7,"sepal width (cm)":2.5,"petal length (cm)":5.0,"petal width (cm)":2.0},{"sepal length (cm)":5.5,"sepal width (cm)":4.2,"petal length (cm)":1.4,"petal width (cm)":0.2},{"sepal length (cm)":6.0,"sepal width (cm)":3.0,"petal length (cm)":4.8,"petal width (cm)":1.8},{"sepal length (cm)":5.8,"sepal width (cm)":2.7,"petal length (cm)":5.1,"petal width (cm)":1.9},{"sepal length (cm)":6.0,"sepal width (cm)":2.2,"petal length (cm)":4.0,"petal width (cm)":1.0},{"sepal length (cm)":5.4,"sepal width (cm)":3.0,"petal length (cm)":4.5,"petal width (cm)":1.5},{"sepal length (cm)":6.2,"sepal width (cm)":3.4,"petal length (cm)":5.4,"petal width (cm)":2.3},{"sepal length (cm)":5.5,"sepal width (cm)":2.3,"petal length (cm)":4.0,"petal width (cm)":1.3},{"sepal length (cm)":5.4,"sepal width (cm)":3.9,"petal length (cm)":1.7,"petal width (cm)":0.4},{"sepal length (cm)":5.0,"sepal width (cm)":2.3,"petal length (cm)":3.3,"petal width (cm)":1.0},{"sepal length (cm)":6.4,"sepal width (cm)":2.7,"petal length (cm)":5.3,"petal width (cm)":1.9},{"sepal length (cm)":5.0,"sepal width (cm)":3.3,"petal length (cm)":1.4,"petal width (cm)":0.2},{"sepal length (cm)":5.0,"sepal width (cm)":3.2,"petal length (cm)":1.2,"petal width (cm)":0.2},{"sepal length (cm)":5.5,"sepal width (cm)":2.4,"petal length (cm)":3.8,"petal width (cm)":1.1},{"sepal length (cm)":6.7,"sepal width (cm)":3.0,"petal length (cm)":5.0,"petal width (cm)":1.7},{"sepal length (cm)":4.9,"sepal width (cm)":3.1,"petal length (cm)":1.5,"petal width (cm)":0.2},{"sepal length (cm)":5.8,"sepal width (cm)":2.8,"petal length (cm)":5.1,"petal width (cm)":2.4},{"sepal length (cm)":5.0,"sepal width (cm)":3.4,"petal length (cm)":1.5,"petal width (cm)":0.2},{"sepal length (cm)":5.0,"sepal width (cm)":3.5,"petal length (cm)":1.6,"petal width (cm)":0.6},{"sepal length (cm)":5.9,"sepal width (cm)":3.2,"petal length (cm)":4.8,"petal width (cm)":1.8},{"sepal length (cm)":5.1,"sepal width (cm)":2.5,"petal length (cm)":3.0,"petal width (cm)":1.1},{"sepal length (cm)":6.9,"sepal width (cm)":3.2,"petal length (cm)":5.7,"petal width (cm)":2.3},{"sepal length (cm)":6.0,"sepal width (cm)":2.7,"petal length (cm)":5.1,"petal width (cm)":1.6},{"sepal length (cm)":6.1,"sepal width (cm)":2.6,"petal length (cm)":5.6,"petal width (cm)":1.4},{"sepal length (cm)":7.7,"sepal width (cm)":3.0,"petal length (cm)":6.1,"petal width (cm)":2.3},{"sepal length (cm)":5.5,"sepal width (cm)":2.5,"petal length (cm)":4.0,"petal width (cm)":1.3},{"sepal length (cm)":4.4,"sepal width (cm)":2.9,"petal length (cm)":1.4,"petal width (cm)":0.2},{"sepal length (cm)":4.3,"sepal width (cm)":3.0,"petal length (cm)":1.1,"petal width (cm)":0.1},{"sepal length (cm)":6.0,"sepal width (cm)":2.2,"petal length (cm)":5.0,"petal width (cm)":1.5},{"sepal length (cm)":7.2,"sepal width (cm)":3.2,"petal length (cm)":6.0,"petal width (cm)":1.8},{"sepal length (cm)":4.6,"sepal width (cm)":3.1,"petal length (cm)":1.5,"petal width (cm)":0.2},{"sepal length (cm)":5.1,"sepal width (cm)":3.5,"petal length (cm)":1.4,"petal width (cm)":0.3},{"sepal length (cm)":4.4,"sepal width (cm)":3.0,"petal length (cm)":1.3,"petal width (cm)":0.2},{"sepal length (cm)":6.3,"sepal width (cm)":2.5,"petal length (cm)":4.9,"petal width (cm)":1.5},{"sepal length (cm)":6.3,"sepal width (cm)":3.4,"petal length (cm)":5.6,"petal width (cm)":2.4},{"sepal length (cm)":4.6,"sepal width (cm)":3.4,"petal length (cm)":1.4,"petal width (cm)":0.3},{"sepal length (cm)":6.8,"sepal width (cm)":3.0,"petal length (cm)":5.5,"petal width (cm)":2.1},{"sepal length (cm)":6.3,"sepal width (cm)":3.3,"petal length (cm)":6.0,"petal width (cm)":2.5},{"sepal length (cm)":4.7,"sepal width (cm)":3.2,"petal length (cm)":1.3,"petal width (cm)":0.2},{"sepal length (cm)":6.1,"sepal width (cm)":2.9,"petal length (cm)":4.7,"petal width (cm)":1.4},{"sepal length (cm)":6.5,"sepal width (cm)":2.8,"petal length (cm)":4.6,"petal width (cm)":1.5},{"sepal length (cm)":6.2,"sepal width (cm)":2.8,"petal length (cm)":4.8,"petal width (cm)":1.8},{"sepal length (cm)":7.0,"sepal width (cm)":3.2,"petal length (cm)":4.7,"petal width (cm)":1.4},{"sepal length (cm)":6.4,"sepal width (cm)":3.2,"petal length (cm)":5.3,"petal width (cm)":2.3},{"sepal length (cm)":5.1,"sepal width (cm)":3.8,"petal length (cm)":1.6,"petal width (cm)":0.2},{"sepal length (cm)":6.9,"sepal width (cm)":3.1,"petal length (cm)":5.4,"petal width (cm)":2.1},{"sepal length (cm)":5.9,"sepal width (cm)":3.0,"petal length (cm)":4.2,"petal width (cm)":1.5},{"sepal length (cm)":6.5,"sepal width (cm)":3.0,"petal length (cm)":5.2,"petal width (cm)":2.0},{"sepal length (cm)":5.7,"sepal width (cm)":2.6,"petal length (cm)":3.5,"petal width (cm)":1.0},{"sepal length (cm)":5.2,"sepal width (cm)":2.7,"petal length (cm)":3.9,"petal width (cm)":1.4},{"sepal length (cm)":6.1,"sepal width (cm)":3.0,"petal length (cm)":4.6,"petal width (cm)":1.4},{"sepal length (cm)":4.5,"sepal width (cm)":2.3,"petal length (cm)":1.3,"petal width (cm)":0.3},{"sepal length (cm)":6.6,"sepal width (cm)":2.9,"petal length (cm)":4.6,"petal width (cm)":1.3},{"sepal length (cm)":5.5,"sepal width (cm)":2.6,"petal length (cm)":4.4,"petal width (cm)":1.2},{"sepal length (cm)":5.3,"sepal width (cm)":3.7,"petal length (cm)":1.5,"petal width (cm)":0.2},{"sepal length (cm)":5.6,"sepal width (cm)":3.0,"petal length (cm)":4.1,"petal width (cm)":1.3},{"sepal length (cm)":7.3,"sepal width (cm)":2.9,"petal length (cm)":6.3,"petal width (cm)":1.8},{"sepal length (cm)":6.7,"sepal width (cm)":3.3,"petal length (cm)":5.7,"petal width (cm)":2.1},{"sepal length (cm)":5.1,"sepal width (cm)":3.7,"petal length (cm)":1.5,"petal width (cm)":0.4},{"sepal length (cm)":4.9,"sepal width (cm)":2.4,"petal length (cm)":3.3,"petal width (cm)":1.0},{"sepal length (cm)":6.7,"sepal width (cm)":3.3,"petal length (cm)":5.7,"petal width (cm)":2.5},{"sepal length (cm)":7.2,"sepal width (cm)":3.0,"petal length (cm)":5.8,"petal width (cm)":1.6},{"sepal length (cm)":4.9,"sepal width (cm)":3.6,"petal length (cm)":1.4,"petal width (cm)":0.1},{"sepal length (cm)":6.7,"sepal width (cm)":3.1,"petal length (cm)":5.6,"petal width (cm)":2.4},{"sepal length (cm)":4.9,"sepal width (cm)":3.0,"petal length (cm)":1.4,"petal width (cm)":0.2},{"sepal length (cm)":6.9,"sepal width (cm)":3.1,"petal length (cm)":4.9,"petal width (cm)":1.5},{"sepal length (cm)":7.4,"sepal width (cm)":2.8,"petal length (cm)":6.1,"petal width (cm)":1.9},{"sepal length (cm)":6.3,"sepal width (cm)":2.9,"petal length (cm)":5.6,"petal width (cm)":1.8},{"sepal length (cm)":5.7,"sepal width (cm)":2.8,"petal length (cm)":4.1,"petal width (cm)":1.3},{"sepal length (cm)":6.5,"sepal width (cm)":3.0,"petal length (cm)":5.5,"petal width (cm)":1.8},{"sepal length (cm)":6.3,"sepal width (cm)":2.3,"petal length (cm)":4.4,"petal width (cm)":1.3},{"sepal length (cm)":6.4,"sepal width (cm)":2.9,"petal length (cm)":4.3,"petal width (cm)":1.3},{"sepal length (cm)":5.6,"sepal width (cm)":2.8,"petal length (cm)":4.9,"petal width (cm)":2.0},{"sepal length (cm)":5.9,"sepal width (cm)":3.0,"petal length (cm)":5.1,"petal width (cm)":1.8},{"sepal length (cm)":5.4,"sepal width (cm)":3.4,"petal length (cm)":1.7,"petal width (cm)":0.2},{"sepal length (cm)":6.1,"sepal width (cm)":2.8,"petal length (cm)":4.0,"petal width (cm)":1.3},{"sepal length (cm)":4.9,"sepal width (cm)":2.5,"petal length (cm)":4.5,"petal width (cm)":1.7},{"sepal length (cm)":5.8,"sepal width (cm)":4.0,"petal length (cm)":1.2,"petal width (cm)":0.2},{"sepal length (cm)":5.8,"sepal width (cm)":2.6,"petal length (cm)":4.0,"petal width (cm)":1.2},{"sepal length (cm)":7.1,"sepal width (cm)":3.0,"petal length (cm)":5.9,"petal width (cm)":2.1}]'

In [20]:
df = pd.read_json(x_train.to_json())
df

C:\Users\Admin\AppData\Local\Temp\ipykernel_10440\1488525998.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(x_train.to_json())

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
22                 4.6               3.6                1.0               0.2
15                 5.7               4.4                1.5               0.4
65                 6.7               3.1                4.4               1.4
11                 4.8               3.4                1.6               0.2
42                 4.4               3.2                1.3               0.2
..                 ...               ...                ...               ...
71                 6.1               2.8                4.0               1.3
106                4.9               2.5                4.5               1.7
14                 5.8               4.0                1.2               0.2
92                 5.8               2.6                4.0               1.2
102                7.1               3.0                5.9               2.1

[120 rows x 4 columns]

In [22]:
y_train.to_json(orient="records")

'[0,0,1,0,0,2,1,0,0,0,2,1,1,0,0,1,2,2,1,2,1,2,1,0,2,1,0,0,0,1,2,0,0,0,1,0,1,2,0,1,2,0,2,2,1,1,2,1,0,1,2,0,0,1,1,0,2,0,0,1,1,2,1,2,2,1,0,0,2,2,0,0,0,1,2,0,2,2,0,1,1,2,1,2,0,2,1,2,1,1,1,0,1,1,0,1,2,2,0,1,2,2,0,2,0,1,2,2,1,2,1,1,2,2,0,1,2,0,1,2]'

In [24]:
df = pd.read_json(y_train.to_json(orient="records")).squeeze()
type(df)

C:\Users\Admin\AppData\Local\Temp\ipykernel_10440\1313253950.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(y_train.to_json(orient="records")).squeeze()

pandas.core.series.Series